# Site settings
title: "Saad Idrissi — Portfolio Étudiant"
description: "Portfolio étudiant cybersécurité : compétences, projets et contact"
email: "idrissisaad340@gmail.com"
baseurl: "/portfolio"
²url: "https://3xpyth0n.github.io"

# Theme
theme: minimal-mistakes-jekyll
plugins:
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-sitemap

# Author
author:
  name: "Saad Idrissi"
  email: "idrissisaad340@gmail.com"

# Social links
social:
  github: "3xpyth0n"
  linkedin: "saaddrs"

# Defaults for pages
defaults:
  -
    scope:
      path: ""
      type: "pages"
    values:
      layout: "single"
      author_profile: true
