title: "Saad Idrissi — Portfolio Étudiant"
description: "Portfolio étudiant cybersécurité : compétences, projets et contact"
email: "idrissisaad340@gmail.com"
baseurl: "" # <-- ici
url: "https://3xpyth0n.github.io"

theme: jekyll-theme-cayman

author:
  name: "Saad Idrissi"
  email: "idrissisaad340@gmail.com"

social:
  github: "3xpyth0n"
  linkedin: "saaddrs"

defaults:
  -
    scope:
      path: ""
      type: "pages"
    values:
      layout: "page"
      author_profile: true

plugins:
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-sitemap

